# Generated by Django 5.2.17 on 2026-09-07 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicecategory',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'Device Category', 'verbose_name_plural': 'Device Categories'},
        ),
        migrations.AlterModelOptions(
            name='devicetype',
            options={'ordering': ['display_order', 'category__name', 'name'], 'verbose_name': 'Device Type', 'verbose_name_plural': 'Device Types'},
        ),
        migrations.AddField(
            model_name='devicecategory',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='is_default',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='OrganizationDeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_name', models.CharField(blank=True, max_length=150)),
                ('custom_description', models.TextField(blank=True)),
                ('manufacturer', models.CharField(blank=True, max_length=150)),
                ('model_family', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('is_custom', models.BooleanField(db_index=True, default=False)),
                ('is_enabled', models.BooleanField(db_index=True, default=True)),
                ('default_quantity', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_device_types', to=settings.AUTH_USER_MODEL)),
                ('custom_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_device_types', to='organizations.devicecategory')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_device_types', to='organizations.organization')),
                ('platform_device_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_instances', to='organizations.devicetype')),
            ],
            options={
                'verbose_name': 'Organization Device Type',
                'verbose_name_plural': 'Organization Device Types',
                'ordering': ['is_custom', 'platform_device_type__category__name', 'custom_name', 'platform_device_type__name'],
            },
        ),
    ]
