# Generated by Django 5.0.14 on 2026-09-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_devicecategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=100000.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=100000.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=100000.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='monthly_base_price',
            field=models.DecimalField(decimal_places=2, default=100000.0, max_digits=12),
        ),
    ]
