# Generated by Django 6.0 on 2026-01-30 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userassethistory',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
