# Generated by Django 6.0 on 2026-01-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userassethistory_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgearticle',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='knowledgearticle',
            name='relevance_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userassethistory',
            name='acknowledged_policy',
            field=models.BooleanField(default=False),
        ),
    ]
