# Generated by Django 6.0 on 2026-02-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_auditlog_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='last_maintenance_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
