# Generated by Django 6.0 on 2026-02-11 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_last_maintenance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetrequest',
            name='additional_requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assetrequest',
            name='days_per_week',
            field=models.CharField(blank=True, default='3-5', max_length=10),
        ),
        migrations.AddField(
            model_name='assetrequest',
            name='hours_per_day',
            field=models.CharField(blank=True, default='4-8', max_length=10),
        ),
        migrations.AddField(
            model_name='assetrequest',
            name='intended_use',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assetrequest',
            name='replacement_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_by_requests', to='core.asset'),
        ),
        migrations.AddField(
            model_name='assetrequest',
            name='required_by_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetrequest',
            name='selected_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_in_requests', to='core.asset'),
        ),
        migrations.AddField(
            model_name='assetrequest',
            name='specifications',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='assetrequest',
            name='supporting_docs',
            field=models.FileField(blank=True, null=True, upload_to='asset_requests/'),
        ),
        migrations.AddField(
            model_name='assetrequest',
            name='urgency',
            field=models.CharField(choices=[('normal', 'Normal (1-2 weeks)'), ('high', 'High (3-7 days)'), ('urgent', 'Urgent (1-3 days)')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='assetrequest',
            name='assigned_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilled_requests', to='core.asset'),
        ),
    ]
