# Generated by Django 5.0.14 on 2026-09-15 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_asset_device_type_asset_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('User', 'User'), ('Technician', 'Technician'), ('ICT Officer', 'ICT Officer'), ('Supervisor', 'Supervisor'), ('HOD', 'HOD'), ('Manager', 'Manager'), ('Admin', 'Admin'), ('SuperAdmin', 'SuperAdmin'), ('PlatformAdmin', 'PlatformAdmin')], default='User', max_length=50),
        ),
    ]
